services:

  foxy-unity-activate:
    build: .
    image: hodgespodge/foxy-unity
    container_name: foxy-unity-activate
    init: true
    environment:
      - DISPLAY
    volumes:
      - ${HOME}/.cache/docker-foxy-unity:/tmp/.local
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /var/run/dbus:/var/run/dbus
    network_mode: "host"
    privileged: true
    entrypoint: [ "/unity_activate.sh" ]

  # foxy-unity-run:
  #   image: hodgespodge/foxy-unity
  #   container_name: foxy-unity-build
  #   init: true
  #   user: ${UID}
  #   environment:
  #     - DISPLAY
  #     - BUILD_NAME
  #   volumes:
  #     - ${HOME}/.cache/docker-foxy-unity:/tmp/.local
